name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]
        browser: [chromium, firefox, webkit]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install chromium dependencies
        if: matrix.browser == 'chromium'
        run: sudo apt-get install libgbm1
      - name: Install webkit dependencies
        if: matrix.browser == 'webkit'
        run: |
          sudo apt-get install libwoff1 libopus0 libwebp6 libwebpdemux2 libenchant1c2a libgudev-1.0-0 libsecret-1-0 libhyphen0 libgdk-pixbuf2.0-0 libegl1 libgles2 libevent-2.1-6 libnotify4 libvpx5 libxslt1.1
      - run: npm install
      - run: npm run lint
      - run: npm run build
      - run: QAW_BROWSER=${{ matrix.browser }} npm test
